import {NgModule} from '@angular/core';

import {
  MatToolbarModule,
  MatButtonModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatInputModule,
  MatTabsModule,
  MatCardModule,
  MatIconModule,
  MatCheckboxModule,
  MatOptionModule,
  MatSelectModule,
  MatDialogModule,
  MatSidenavModule,
  MatRadioModule,
  MatListModule,
  MatDividerModule,
  MatStepperModule,
  MatButtonToggleModule,
  MatSliderModule,
  MatAutocompleteModule,
  MatSlideToggleModule,
  MatProgressBarModule,
  MatTooltipModule,
  MatPaginatorModule,
  MatMenuModule,
  MatTableModule,
  MatChipsModule,
  MatDatepickerModule,

} from '@angular/material';


@NgModule({
  imports: [
    MatToolbarModule,
    MatButtonModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatInputModule,
    MatTabsModule,
    MatCardModule,
    MatIconModule,
    MatCheckboxModule,
    MatOptionModule,
    MatSelectModule,
    MatDialogModule,
    MatSidenavModule,
    MatRadioModule,
    MatListModule,
    MatDividerModule,
    MatStepperModule,
    MatButtonToggleModule,
    MatSliderModule,
    MatAutocompleteModule,
    MatSlideToggleModule,
    MatProgressBarModule,
    MatTooltipModule,
    MatPaginatorModule,
    MatMenuModule,
    MatTableModule,
    MatChipsModule,
    MatDatepickerModule
  ],
  exports: [
    MatToolbarModule,
    MatButtonModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatInputModule,
    MatTabsModule,
    MatCardModule,
    MatIconModule,
    MatCheckboxModule,
    MatOptionModule,
    MatSelectModule,
    MatDialogModule,
    MatSidenavModule,
    MatRadioModule,
    MatListModule,
    MatDividerModule,
    MatStepperModule,
    MatButtonToggleModule,
    MatSliderModule,
    MatAutocompleteModule,
    MatSlideToggleModule,
    MatProgressBarModule,
    MatTooltipModule,
    MatPaginatorModule,
    MatMenuModule,
    MatTableModule,
    MatChipsModule,
    MatDatepickerModule
  ]
})

export class AppMaterialModule { }
